version: '3.7'

services:
  mssql:
    image: mcmoe/mssqldocker
    container_name: example-mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssword
      MSSQL_DB: example
      MSSQL_USER: example
      MSSQL_PASSWORD: P@ssword
    volumes:
      - ./setup/setup-mssql.sql:/usr/config/setup.sql
    ports:
      - 1433:1433
    expose:
      - 1433

  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: example-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:3.6.1
    container_name: example-kafka
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  kowl:
    image: quay.io/cloudhut/kowl:v1.2.2
    container_name: example-kowl
    restart: on-failure
    hostname: kowl
    volumes:
      - ./config/kowl.yaml:/etc/kowl/local.yaml
    ports:
      - "8085:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/local.yaml
    depends_on: 
    - kafka

  kafka-connect:
    image: bitnami/kafka:3.6.1
    container_name: example-kafka-connect
    volumes:
      - ./config/connect-standalone.properties:/opt/bitnami/kafka/config/connect-standalone.properties
      - ./config/connect-mssql-source.properties:/opt/bitnami/kafka/config/connect-mssql-source.properties
      - ./config/connect-log4j.properties:/opt/bitnami/kafka/config/connect-log4j.properties
      - ./libs/connectors:/opt/bitnami/kafka/libs/connectors
      - ./libs/jdbc-drivers/mssql-jdbc-12.4.2.jre11.jar:/opt/bitnami/kafka/libs/mssql-jdbc-12.4.2.jre11.jar
      - ./libs/jdbc-drivers/postgresql-42.2.10.jar:/opt/bitnami/kafka/libs/postgresql-42.2.10.jar
    ports:
      - 8083:8083
    expose:
      - 8083
    depends_on:
      - kafka
      - mssql
    command: /opt/bitnami/kafka/bin/connect-standalone.sh /opt/bitnami/kafka/config/connect-standalone.properties /opt/bitnami/kafka/config/connect-mssql-source.properties